title: beliefmaker
description: Common belief in action - Project Site for Final Project in Logical Aspects of Multi-Agent Systems.
show_downloads: false
google_analytics:
theme: jekyll-theme-leap-day
